language: perl
perl:
  - "5.22"

install:
  - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=c HARNESS_TIMER=1
  - cpanm --quiet --notest --installdeps .

script:
  - prove -lrsv t
  
